// NeuropackModule.cpp — Module entry point + Blueprint function library impl.

#include "NeuroPack.h"
#include "Modules/ModuleManager.h"

// ── C FFI declarations ─────────────────────────────────────────────────────
// These must match the symbols exported by neuropack.dll / libneuropack.so.
// The canonical declaration is in neuropack.h (generated by cbindgen or
// maintained manually).  We inline minimal declarations here to avoid
// requiring the header in the Unreal build system.

extern "C"
{
    const char* neuropack_last_error();
    void*       neuropack_open(const char* path);
    void        neuropack_close(void* handle);
    int         neuropack_read_asset(void* handle, const char* rel_path,
                                     uint8_t** out_data, size_t* out_len);
    void        neuropack_free_asset(uint8_t* data, size_t len);
    size_t      neuropack_entry_count(const void* handle);
    size_t      neuropack_entry_path(const void* handle, size_t i,
                                     char* buf, size_t buf_len);
    uint64_t    neuropack_entry_size(const void* handle, size_t i);
}

// ── Module ─────────────────────────────────────────────────────────────────

class FNeuropackModule : public IModuleInterface
{
public:
    virtual void StartupModule() override
    {
        UE_LOG(LogTemp, Log, TEXT("NeuroPack module loaded."));
    }

    virtual void ShutdownModule() override
    {
        UE_LOG(LogTemp, Log, TEXT("NeuroPack module unloaded."));
    }
};

IMPLEMENT_MODULE(FNeuropackModule, NeuroPack)

// ── UNeuropackLibrary ──────────────────────────────────────────────────────

FNeuropackHandle UNeuropackLibrary::OpenPackage(const FString& FilePath)
{
    const FString NativePath = FPaths::ConvertRelativePathToFull(FilePath);
    void* Ptr = neuropack_open(TCHAR_TO_UTF8(*NativePath));
    if (!Ptr)
    {
        UE_LOG(LogTemp, Warning, TEXT("NeuroPack: OpenPackage failed: %s"),
               UTF8_TO_TCHAR(neuropack_last_error()));
    }
    return FNeuropackHandle(Ptr);
}

void UNeuropackLibrary::ClosePackage(FNeuropackHandle Handle)
{
    if (Handle.IsValid())
    {
        neuropack_close(Handle.Ptr);
    }
}

bool UNeuropackLibrary::ReadAsset(FNeuropackHandle Handle,
                                  const FString& RelPath,
                                  TArray<uint8>& OutBytes)
{
    if (!Handle.IsValid())
    {
        UE_LOG(LogTemp, Warning, TEXT("NeuroPack: ReadAsset called with invalid handle."));
        return false;
    }

    uint8_t* Data  = nullptr;
    size_t   Len   = 0;
    const int Ret  = neuropack_read_asset(Handle.Ptr,
                                          TCHAR_TO_UTF8(*RelPath),
                                          &Data, &Len);
    if (Ret != 0)
    {
        UE_LOG(LogTemp, Warning, TEXT("NeuroPack: ReadAsset('%s') failed: %s"),
               *RelPath, UTF8_TO_TCHAR(neuropack_last_error()));
        return false;
    }

    OutBytes.SetNumUninitialized((int32)Len);
    FMemory::Memcpy(OutBytes.GetData(), Data, Len);
    neuropack_free_asset(Data, Len);
    return true;
}

int32 UNeuropackLibrary::GetEntryCount(FNeuropackHandle Handle)
{
    return Handle.IsValid() ? (int32)neuropack_entry_count(Handle.Ptr) : 0;
}

FString UNeuropackLibrary::GetEntryPath(FNeuropackHandle Handle, int32 Index)
{
    if (!Handle.IsValid()) return FString();
    char Buf[1024] = {};
    neuropack_entry_path(Handle.Ptr, (size_t)Index, Buf, sizeof(Buf));
    return FString(UTF8_TO_TCHAR(Buf));
}

int64 UNeuropackLibrary::GetEntrySize(FNeuropackHandle Handle, int32 Index)
{
    return Handle.IsValid() ? (int64)neuropack_entry_size(Handle.Ptr, (size_t)Index) : 0;
}

FString UNeuropackLibrary::GetLastError()
{
    return FString(UTF8_TO_TCHAR(neuropack_last_error()));
}
